# Generated by Django 3.0.4 on 2020-03-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_in_pa', models.CharField(choices=[('FD', 'อาหาร'), ('DK', 'เครื่องดื่ม'), ('SK', 'ขนม')], default='FD', max_length=2)),
                ('product_price', models.IntegerField(default=0)),
            ],
        ),
    ]
