# Generated by Django 3.0.4 on 2020-03-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_auto_20200308_2047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='type',
            new_name='product_type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='product_type',
        ),
    ]
