# Generated by Django 3.0.4 on 2020-03-10 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0003_auto_20200309_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='POS.Product_type'),
        ),
    ]
