# Generated by Django 3.0.4 on 2020-03-11 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0005_auto_20200311_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.TimeField()),
                ('total_price', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Type',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='POS.Product_type'),
        ),
        migrations.CreateModel(
            name='Order_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('order_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='POS.Order')),
                ('product_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='POS.Product')),
            ],
        ),
    ]
