# Generated by Django 3.0.4 on 2020-03-11 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0006_auto_20200311_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_products',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order_products',
            name='product_id',
        ),
        migrations.AddField(
            model_name='order_products',
            name='order',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='POS.Order'),
        ),
        migrations.AddField(
            model_name='order_products',
            name='product',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='POS.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Type',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='POS.Product_type'),
        ),
    ]
